In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
df = pd.read_table("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt", delim_whitespace=True, comment='#', header=None)

/Users/flatironschool/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.

In [4]:
newdf = df[[0,1,3]]

In [5]:
names= ["year", "month","co2"]
newdf.columns = names
newdf

     year  month     co2
0    1958      3  315.71
1    1958      4  317.45
2    1958      5  317.50
3    1958      6  -99.99
4    1958      7  315.86
5    1958      8  314.93
6    1958      9  313.20
7    1958     10  -99.99
8    1958     11  313.33
9    1958     12  314.67
10   1959      1  315.62
11   1959      2  316.38
12   1959      3  316.71
13   1959      4  317.72
14   1959      5  318.29
15   1959      6  318.15
16   1959      7  316.54
17   1959      8  314.80
18   1959      9  313.84
19   1959     10  313.26
20   1959     11  314.80
21   1959     12  315.58
22   1960      1  316.43
23   1960      2  316.97
24   1960      3  317.58
25   1960      4  319.02
26   1960      5  320.03
27   1960      6  319.59
28   1960      7  318.18
29   1960      8  315.91
..    ...    ...     ...
703  2016     10  401.59
704  2016     11  403.55
705  2016     12  404.45
706  2017      1  406.17
707  2017      2  406.46
708  2017      3  407.22
709  2017      4  409.04
710  2017      5  409.69
711  2017      6  408.88
712  2017      7  407.12
713  2017      8  405.13
714  2017      9  403.37
715  2017     10  403.63
716  2017     11  405.12
717  2017     12  406.81
718  2018      1  407.96
719  2018      2  408.32
720  2018      3  409.41
721  2018      4  410.24
722  2018      5  411.24
723  2018      6  410.79
724  2018      7  408.71
725  2018      8  406.99
726  2018      9  405.51
727  2018     10  406.00
728  2018     11  408.02
729  2018     12  409.07
730  2019      1  410.83
731  2019      2  411.75
732  2019      3  411.97

[733 rows x 3 columns]

In [6]:
for i in range(len(newdf['co2'])):
    if float(newdf['co2'].loc[i]) == -99.99: 
        newdf['co2'].loc[i] = np.nan
        #print(newdf['co2'].loc[i])

/Users/flatironschool/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/Users/flatironschool/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [7]:
newdf.head()

   year  month     co2
0  1958      3  315.71
1  1958      4  317.45
2  1958      5  317.50
3  1958      6     NaN
4  1958      7  315.86

In [32]:
# convert year and month column to string
newdf['year'] = newdf['year'].map(lambda x: str(x))
newdf['month'] = newdf['month'].map(lambda x :str(x))

/Users/flatironschool/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/flatironschool/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [43]:
newdf = pd.get_dummies(newdf)

In [38]:
from sklearn.preprocessing import StandardScaler

In [66]:
np.where(newdf['co2']== np.nan)
newdf = newdf.dropna()
newdf.reset_index(drop=True)
#newdf2
#ss = StandardScaler()
#co2_std = ss.fit_transform(newdf['co2'].values)

,co2,year_1958,year_1959,year_1960,year_1961,year_1962,year_1963,year_1964,year_1965,year_1966,...,month_11,month_12,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9
0,315.71,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,317.45,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,317.50,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,315.86,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,314.93,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5,313.20,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,313.33,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7,314.67,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,315.62,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,316.38,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
10,316.71,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
11,317.72,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
12,318.29,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13,318.15,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,316.54,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15,314.80,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
16,313.84,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,313.26,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,314.80,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,315.58,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
20,316.43,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,316.97,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22,317.58,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23,319.02,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
24,320.03,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
25,319.59,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,318.18,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
27,315.91,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
28,314.16,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
29,313.83,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696,401.59,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,403.55,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
698,404.45,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
699,406.17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
700,406.46,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
701,407.22,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
702,409.04,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
703,409.69,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
704,408.88,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
705,407.12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
706,405.13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
707,403.37,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
708,403.63,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
709,405.12,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
710,406.81,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
711,407.96,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
712,408.32,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
713,409.41,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
714,410.24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
715,411.24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
716,410.79,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
717,408.71,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
718,406.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
719,405.51,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
720,406.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
721,408.02,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
722,409.07,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
723,410.83,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
724,411.75,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
725,411.97,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [70]:
ss = StandardScaler()
co2_std = ss.fit_transform(newdf[['co2']].values)